log_level: INFO
remove_frame_data: true
redis:
  host: redis
  port: 6379
target_redis:
  host: redis
  port: 6379
  buffer_length: 10                   # How many messages the internal ring buffer will hold before discarding old messages
  target_stream_maxlen: 100           # maxlen for redis XADD (Redis will delete oldest messages from stream to stay within maxlen)
  tls: false                          # Whether to use mutual TLS for communication. See README for details on how to configure.

# this configures mapping between source and target streams 
# if no target name is configured, source stream will be forwarded to target stream of the same name
mapping_config:
  - source: geomapper:device01
  - source: positionsource:self
    target: positionsource:other

prometheus_port: 8000