#!/bin/bash
set -e

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then
    echo "Object Detector: Installing Python dependencies"
    pip3 install --upgrade pip
    pip3 install pyturbojpeg
    pip3 install git+https://github.com/starwit/vision-api.git@3.2.0#subdirectory=python/visionapi
    pip3 install git+https://github.com/starwit/vision-lib.git@0.11.2#subdirectory=python

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/rediswriter <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/rediswriter

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/rediswriter    

    # link settings file from etc
    cd /opt/starwit/rediswriter
    ln -s /etc/starwit/rediswriter/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start rediswriter.service        
    systemctl enable rediswriter.service
fi

#DEBHELPER#

exit 0