#!/bin/bash
set -e

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then

    echo "Create virtual environment for application"
    cd "/opt/starwit/rediswriter"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt 

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/rediswriter <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/rediswriter
source .venv/bin/activate

python main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/rediswriter    

    # link settings file from etc
    cd /opt/starwit/rediswriter
    ln -s /etc/starwit/rediswriter/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start rediswriter.service        
    systemctl enable rediswriter.service
fi

#DEBHELPER#

exit 0