#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    # Stop the service
    systemctl stop rediswriter.service

    # Disable the service
    systemctl disable rediswriter.service

    # Remove the service file
    rm -f /etc/systemd/system/rediswriter.service

    systemctl daemon-reload

    # Remove the wrapper script
    rm -f /usr/local/bin/rediswriter
    
    # Remove application directory
    rm -rf /opt/starwit/rediswriter

    # Remove config files directory
    rm -rf /etc/starwit/rediswriter
fi

#DEBHELPER#

exit 0